#!/usr/bin/env python
import os, sys

tests= [
	("hello", [ "debug", "release" ]),
	("manyfiles", [ "" ]),
	("multiplatform", [ "" ]),
	("staticlib", [ "" ])
]

if __name__ == "__main__":
	clean_str= ""
	if len(sys.argv) > 1:
		clean_str= "clean"
	log= []
	failures= 0
	os.chdir("./tests")
	for name, tags in tests:
		os.chdir(name)
		for tag in tags:
			# Build
			ret= os.system("../../clbs " + tag + " " + clean_str)
			if ret == 0:
				log.append("  " + name + " " + tag + " " + clean_str)
			else:
				failures += 1
				log.append("* " + name + " " + tag + " " + clean_str)
			print("")

		os.chdir("..")

	if failures == 0:
		print("*** All tests completed ***")
	else:
		print("*** FAILED TESTS (" + str(failures) + ") ***")

	for row in log:
		print(row)

