#!/usr/bin/env python
import os, sys

tests= [
	("hello", [ "debug", "release" ]),
	("manyfiles", [ "" ]),
	("multiplatform", [ "" ]),
	("staticlib", [ "" ])
]

if __name__ == "__main__":
	args= ""
	if len(sys.argv) > 1:
		args= " ".join(sys.argv[1:])
	log= []
	failures= 0
	os.chdir("./tests")
	for name, targets in tests:
		os.chdir(name)
		for target in targets:
			ret= os.system("../../clbs " + target + " " + args)
			if ret == 0:
				log.append("  " + name + " " + target + " " + args)
			else:
				failures += 1
				log.append("* " + name + " " + target + " " + args)
			print("")

		os.chdir("..")

	if failures == 0:
		print("*** All tests completed ***")
	else:
		print("*** FAILED TESTS (" + str(failures) + ") ***")

	for row in log:
		print(row)

